-- https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function ()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("waybar")
  hl.exec_cmd("clipse -listen")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("elephant")
  hl.exec_cmd("hyprpaper")
  -- for Screen Sharing(https://wiki.hypr.land/Useful-Utilities/Screen-Sharing/#screensharing)
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
