-- local convertT = {
-- 	denols = "deno",
-- 	ts_ls = "tsserver",
-- }
--
-- ---@param key string
-- local function getOptions(key)
-- 	local neoconf = require("neoconf")
--
-- 	local schemaT = vim.iter({ "", "vscode", "coc", "nlsp" }):map(function(configType)
-- 		return configType == "" and key or ("%s.%s"):format(configType, key)
-- 	end)
--
-- 	---@type nil|string|table|integer|boolean
-- 	local item = vim.iter(schemaT)
-- 		:map(function(item)
-- 			return neoconf.get(item)
-- 		end)
-- 		:find(function(item)
-- 			return item ~= nil
-- 		end)
-- 	return item
-- end
--
-- --@param name string
-- local function isClientEnable(name)
-- 	local client_name_key = convertT[name] or name
-- 	local enable = getOptions(client_name_key .. ".enable")
-- 	local disable = getOptions(client_name_key .. ".disable")
-- 	if enable == nil and disable == nil then
-- 		return nil
-- 	end
--
-- 	local isEnable = enable == true or disable == false
-- 	return isEnable
-- end
--
return {
-- 	"folke/neoconf.nvim",
-- 	opts = {},
-- 	config = function(_, opts)
-- 		local neoconf = require("neoconf")
-- 		neoconf.setup(opts)
-- 		local neoconf_augroup = vim.api.nvim_create_augroup("NeoconfLspManagement", { clear = true })
-- 		vim.api.nvim_create_autocmd("LspAttach", {
-- 			group = neoconf_augroup,
-- 			desc = "neoconf: Detach disabled LSP clients on buffer attach",
-- 			callback = function(args)
-- 				local bufnr = args.buf
-- 				local client_id = args.data.client_id
-- 				local client = vim.lsp.get_client_by_id(client_id)
--
-- 				if not client or not client.name then
-- 					return
-- 				end
--
-- 				local client_name = client.name
-- 				local isEnable = isClientEnable(client_name)
-- 				if isEnable == false then
-- 					vim.lsp.buf_detach_client(bufnr, client.id)
-- 				elseif isEnable == true then
-- 				else
-- 				end
-- 			end,
-- 		})
-- 	end,
-- 	getOptions = getOptions,
}
